public enum InteractiveObjectEnum
{
    NormalBirds = 0,
    MassNormalBirds,
    MassAsteroids,
    MassCoins,
    MassBoostSpeed,
    BigCoin,
    BoostMagnet,
    BoostJetpack,
    BoostShield,
    BoostSpeed,
    SpaceShip,
    MassClouds,
    BigCristal,
    BigCloudRain,
    Airplane,
    Star,
    MassStars,
}
